#pragma once
#define IBEX_ENCRYPTION_SUCCESS							0
#define IBEX_ENCRYPTION_BASE							10000
#define IBEX_ENCRYPTION_BUFFER_EMPTY					(IBEX_ENCRYPTION_BASE + 101)
#define IBEX_ENCRYPTION_KEY_INVALID						(IBEX_ENCRYPTION_BASE + 102)
#define IBEX_ENCRYPTION_FILE_EMPTY						(IBEX_ENCRYPTION_BASE + 103)
#define IBEX_ENCRYPTION_FILE_OPEN_FAILED				(IBEX_ENCRYPTION_BASE + 104)
#define IBEX_ENCRYPTION_INIT_FAILED						(IBEX_ENCRYPTION_BASE + 105)
#define IBEX_ENCRYPTION_UPDATE_FAILED					(IBEX_ENCRYPTION_BASE + 106)
#define IBEX_ENCRYPTION_FINAL_FAILED					(IBEX_ENCRYPTION_BASE + 107)
#define IBEX_ENCRYPTION_EXCEPTION						(IBEX_ENCRYPTION_BASE + 108)
